### ISSUE TITLE
Unable to Install (No Releases)

### ISSUE THREAD

**Issue by rgcarr** [tyler36/ddev-xhgui#1]
There are currently no releases for this package, so `ddev get tyler36/ddev-xhgui` fails with 'No releases found for ddev-xhgui`

I'm using DDEV 1.21.6

Do you have any other recommendations?

**Comment by rfay** [comment]
Hi @rgcarr - You can `ddev get https://github.com/tyler36/ddev-xhgui/tarball/main`

But the fact that it doesn't yet have a release and doesn't have the ddev-get label may mean that @tyler36 isn't ready for people to look at it.

**Comment by rgcarr** [comment]
Thank @rfay - I wasn't sure how else to install it into DDEV

**Comment by tyler36** [comment]
Thats correct. 

I started porting over the DDEV contrib instructions but haven't gotten around to finished it; thats why there's no release or tag yet.

Contributions are welcome, if you have the time.

**Comment by deviantintegral** [comment]
Looks like there's a bug lurking here too!

```
ddev get https://github.com/tyler36/ddev-xhgui/tarball/main
Downloading https://github.com/tyler36/ddev-xhgui/tarball/main
main_3342562574.tar.gz 31.22 KiB / ? [----------------------------------------------------------------------------------------------------------=] 319.69% 0s

Installing project-level components:
Unable to expand files and directories: stat xhgui/config.default.php: no such file or directory
```

**Comment by tyler36** [comment]
Thanks to @deviantintegral ( #4  ), there is now a `0.1` release available.
