### ISSUE TITLE
Unwilling to remove 'xhprof_prepend.php' because it does not have #ddev-generated in it: 

### ISSUE THREAD

**Issue by rfay** [tyler36/ddev-xhgui#11]
I removing the add-on I got the message
`Unwilling to remove '/Users/rfay/workspace/d10/.ddev/xhprof/xhprof_prepend.php' because it does not have #ddev-generated in it: signature was not found in file /Users/rfay/workspace/d10/.ddev/xhprof/xhprof_prepend.php; you can manually delete it if it is safe to delete.
`
I saw a comment about this in xhprof_prepend.php added here, but I don't think this is a good approach, we should figure out a proper way to add the xhprof_prepend.php that you want, or figure something out.

**Comment by tyler36** [comment]
For reference: `.ddev/xhprof/xhprof_prepend.php` @ `0.2`
```
<?php

// ddev's built in xhprof handler breaks our own. If we leave ddev-generated in
// this file, then ddev xhprof will overwrite this file.
return;
```

**Comment by rfay** [comment]
In the current setup, it may be worth considering deleting this in `removal_actions`. But this really is problematic.

How about overriding the docker-compose to remove the mount of .ddev/xhprof? That's hard, but in latest docker-compose I think there's a way to do it. It is hard though. Or it's possible we need some feature in DDEV to turn off the mounting or do it another way.
