### ISSUE TITLE
[enhancement] prevent working in production

### ISSUE THREAD

**Issue by Firesphere** [tyler36/ddev-xhgui#12]
It is possible (although, if I recall, advised against) to use DDEV as a production environment, but even a direct deployment from a git repository that holds the `.ddev` folder and with it, the profiler files might encounter a situation in which the profiler is accidentally running.
An example where this might happen, is e.g. on platform.sh, where I noticed that a standard composer project, installs _with_ composer dev requirements.

It might be good to have a way to ensure the profiler isn't running in a production environment, even if the required xhgui php files exist in the expected location and/or the php-profiler package is installed.

**Comment by rfay** [comment]
I guess IMO people have to sort these things out if they use [Casual hosting](https://ddev.readthedocs.io/en/latest/users/topics/hosting/?h=casual) or use it for other similar purposes. (Lots of people use it for github tests, etc.)

**Comment by tyler36** [comment]
PRs are welcome.

My feeling is DDEV is for local (or cloud) development and testing and therefore it's not the addons responsibility.
Developers are free to use `ddev service disable` or wrap the profiler commands with ENV checkers.

Let's get the addon to a solid place first and then see where the currents flow. 

Closing but happy to open with demand.
