### ISSUE TITLE
xhgui-mongo database is not deleted when addon is removed

### ISSUE THREAD

**Issue by tyler36** [tyler36/ddev-xhgui#14]
Comment by @rfay in https://github.com/tyler36/ddev-xhgui/pull/5#pullrequestreview-1723859678

> I note that the volume for the mongo stuff (ddev-d10_xhgui-mongo) doesn't get deleted when the add-on is removed (but it would on ddev delete I think). That might be a thing to do in a follow-up.

**Comment by rfay** [comment]
There's also a related problem. If you have xhgui running (and the mongo service), and you remove the add-on, the mongo service container doesn't get stopped, leading to a variety of problems.  (And of course the volume can't be removed until that's stopped anyway)

Perhaps we have to force a `ddev stop` before finishing the removal? Not sure. Or we have to insist on the project being stopped before removal?

**Comment by rfay** [comment]
Related:
* https://github.com/tyler36/ddev-xhgui/pull/17

**Comment by tyler36** [comment]
Fixed with #22 

The addon now uses default project database.
