### ISSUE TITLE
Does it work outside of a framework or composer?

### ISSUE THREAD

**Issue by hanoii** [tyler36/ddev-xhgui#19]
I was trying out xhprof on ddev for the first time and submitted https://github.com/ddev/ddev/issues/5532.

I am about to try this on Drupal, but I was curious about this.

**Comment by tyler36** [comment]
It _should_ work without a framework or composer. 

This addon provides the endpoint, xhgui (and mongo database storage). As long as you code loads collectors and sends them to xhgui, I think you'll be find.
Check out: https://github.com/perftools/xhgui#profiling-a-web-request-or-cli-script

**Comment by tyler36** [comment]
Closing.

PRs are welcome if you want to add no-framework or no-composer setup steps to the docs.
