### ISSUE TITLE
Only one Mongo instance allowed at a time

### ISSUE THREAD

**Issue by Firesphere** [tyler36/ddev-xhgui#20]
Due to the port exposing of the Mongo container, if I want to spin up another DDEV project with XHGUI, it will fail because the container can't bind to the port.

**Comment by tyler36** [comment]
Does #16 resolve this for you?

**Comment by Firesphere** [comment]
Okay, this is me being dumb... How do I do `ddev get` and pull in that specific branch? 🤦

**Comment by tyler36** [comment]
IIRC, you replace `tree` with `tarball` in the URL

```diff
- https://github.com/tyler36/ddev-xhgui/tree/13-Investigate-using-official-mongo-addon-for-database
+ https://github.com/tyler36/ddev-xhgui/tarball/13-Investigate-using-official-mongo-addon-for-database
```

Then:

```
ddev get ddev/ddev-mongo
ddev get https://github.com/tyler36/ddev-xhgui/tarball/13-Investigate-using-official-mongo-addon-for-database
```

**Comment by rfay** [comment]
However, the `ports` statement in the current version is just a mistake. It should be `expose`.

**Comment by Firesphere** [comment]
Right, it was tarball, not the zip link...

Back to my question, yes, using branch #13 solves the problem 🎉

**Comment by tyler36** [comment]
Thanks for confirming!
