### ISSUE TITLE
Question/Feedback about the README.md

### ISSUE THREAD

**Issue by rpkoller** [tyler36/ddev-xhgui#23]
I was testing https://github.com/ddev/ddev/pull/5574.  after testing the functionality of xhprof @rfay asked if i could also test ddev-xhgui with php8.3.0. in short it works  - at least from a none developer perspective like mine ;) 
But I've noticed one detail in the README.md that confused me setting up xhgui. Maybe it might be clarified. I was following the instructions using xhgui for a Drupal site. The thing that confused me was why do i have to run `ddev xhprof`at the end of the "Framework  configuration" section while I have to run `ddev xhgui`in the usage section. Is running `ddev xhprof` necessary at all? cuz when you are recording your interaction with your site that is getting saved into mongodb and https://myownsite.ddev.site/xhprof doesnt have any existing runs list, xhgui in contrast has. so the question is could the `ddev xhprof`step  under "Framework configuration" be striked or is it actually necessary (does xhgui needs a running xhprof)? if the latter is the case it might make sense to add an additional note about the reason? in the current state it was just a little bit confusing and made me think as a novice user.

**Comment by tyler36** [comment]
From my understanding:

- `ddev xhprof` turns on PHP profiling extensions, similiar to why `ddev xdebug` does
- `ddev xhgui` launches the GUI 

PRs are always welcome. 😄

**Comment by rpkoller** [comment]
Thanks!I've just created an initial rough draft. Removed some redundancy and tried to make the steps more clear. Plus I've also noticed some XHGui wordmarks just in lower case.

**Comment by tyler36** [comment]
Thank you @rpkoller !

**Comment by tyler36** [comment]
Closing.

See https://github.com/ddev/ddev-xhgui/pull/24 for discussion.

Happy to continue the conversation and improve documentation.
