### ISSUE TITLE
Consider for promotion to ddev/ddev-xhgui

### ISSUE THREAD

**Issue by rfay** [tyler36/ddev-xhgui#3]
When you think this is ready, please consider promotion to ddev namespace. 

Related: 
* https://github.com/ddev/ddev/issues/4606

**Comment by tyler36** [comment]
@deviantintegral did a lot of clean-up on the files.

Once we cleanup the docs and add some good tests, I intend to request promotion.

**Comment by tyler36** [comment]
Repository was transfered a few minutes ago.

Keep this issue open until we cleanup the docs ("tyler36/ddev-xhgui" => "ddev/ddev-xhgui")

**Comment by rfay** [comment]
Yippee!

**Comment by rfay** [comment]
Gotta read the whole sentence.
