### ISSUE TITLE
Update wordpress instructions 

### ISSUE THREAD

**Issue by nickchomey** [tyler36/ddev-xhgui#38]
In the non-bedrock instructions for wordpress, it says to to download v0.18, which is 3.5 years and 9 releases old... 

It would be far better to just instruct to `git clone https://github.com/perftools/php-profiler.git` the repo.

Then the addition to wp-config.php could just point to `require_once __DIR__ . '/php-profiler/autoload.php';`

**Comment by rfay** [comment]
PR is welcome, thanks!

**Comment by tyler36** [comment]
Fixed in #39
